Sobrecarga de métodos
disfordavidd/rest_test pull request #11
Opened 2024-06-28 03:58 UTC by disfordavidd

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Link to JIRA task

https://25maikelo.atlassian.net/browse/LABSHARE-19

## Description (What/Why/How has changed)

Se añadieron funcionalidades simples adicionales para los métodos CRUD.
Para Create, se añadió un mensaje de éxito.
Para List, se enlistan solo las sillas disponibles.
Para Get, se añade un contador de visitas para cada silla.
Para Destroy, se añade un mensaje de éxito.

## Images/Screenshots

![image](https://github.com/disfordavidd/rest_test/assets/154297795/925b71a0-4982-456d-85e6-4deceaa9170f)

![image](https://github.com/disfordavidd/rest_test/assets/154297795/a5a60efe-1c09-4266-90d3-002e0a746b34)

![image](https://github.com/disfordavidd/rest_test/assets/154297795/e7b27a30-de78-4a1e-82b3-19f0bf8d10be)

## What reviewer should know

## [optional] What gif best describes this PR or how it makes you feel?

![alt_text](gif_link)

2024-06-28 19:41 UTC, 25maikelo requested changes

2024-06-28 19:41 UTC, 25maikelo commented on test_site/settings.py
Justifica el import sys

2024-06-30 02:54 UTC, disfordavidd commented on test_site/settings.py
Era para un tutorial de las pruebas unitarias, no lo utilicé. Ya lo borré

2024-06-30 22:16 UTC, 25maikelo approved these changes
Muy bien! 👍🏻

2024-06-30 22:16 UTC, merged