Practica 2 MVC
disfordavidd/rest_test pull request #3
Opened 2024-05-19 03:45 UTC by jmDevstro

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [+] Documentation Update

## Link to JIRA task
https://25maikelo.atlassian.net/jira/software/projects/LABSHARE/boards/1?selectedIssue=LABSHARE-9

## Description (What/Why/How has changed)
- Se añadió app Juan
- Se creo el modelo lampara y su respectivo CRUD en la ruta /api/lampara/ a nivel de RESTFRAMEWORK
- Se creo interfaz front que utilice los endpoints CRUD del API en la ruta /lamparas/

## Images/Screenshots

## What reviewer should know
- Se agregó en settings.py la config 'SITE_URL' para estabecer el dominio por defecto: "http://localhost:3000", se deberá ajustar al ejecutarse con otro dominio

## [optional] What gif best describes this PR or how it makes you feel?

![alt_text](gif_link)

2024-05-20 20:38 UTC, 25maikelo requested changes

2024-05-20 20:38 UTC, 25maikelo commented on Juan/middleware.py
No es necesario el Middleware para esta práctica

2024-05-20 20:38 UTC, 25maikelo commented on Juan/templates/editarlampara.html
Las vistas se debieron crear atuomaticamente con restframework, en esta parte no hay que implementar django templates, para poder probar el rendimiento de la API primero.

2024-05-20 20:38 UTC, 25maikelo commented on Juan/urls.py
> +urlpatterns = routerl.urls
urlpatterns debe ser un arreglo o tupla ya que es una variable que se usa en todo el contexto del proyecto

2024-05-20 20:38 UTC, 25maikelo commented on Juan/views.py
> +        })
Todas las vistas debieron ser creadas con restframework y en una sola clase, recordemos que la definición de meétodos debe quedar en su mayoría dentro de clases. Restframework proporciona herencia de clase para todos los métodos CRUD, ya sea un APIView o que tu puedas obtener solo la que necesitas. Para esta práctica se deben implementar todos los métodos.

2024-05-20 20:38 UTC, 25maikelo commented on test_site/urls.py
> +    path("lamparas/edit/", lamparaEditar),
Deberías de ser capaz de agregar todos los métodos en una sola línea de codigo por el uso de resframework.

2024-05-22 03:41 UTC, jmDevstro commented
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [+] Documentation Update


## Link to JIRA task
https://25maikelo.atlassian.net/jira/software/projects/LABSHARE/boards/1?selectedIssue=LABSHARE-9



## Description (What/Why/How has changed)
- Se añadió app Juan
- Se actualizó el proyecto para que utilice solo el CRUD con RESTFRAMEWORK en la ruta /lampara/


## Images/Screenshots
![Practica2](https://github.com/disfordavidd/rest_test/assets/166676973/4a0ec9a2-8660-4722-a3bd-b60a612c0c0f)




## What reviewer should know



## [optional] What gif best describes this PR or how it makes you feel?

![alt_text](gif_link)

2024-05-24 13:26 UTC, 25maikelo approved these changes

2024-05-24 13:26 UTC, 25maikelo commented on Juan/urls.py
> +urlpatterns = routerl.urls
Aún falta corregir esto

2024-05-24 13:26 UTC, merged