Añadida app David y modelo con serializadores CRUD
disfordavidd/rest_test pull request #4
Opened 2024-05-20 05:11 UTC by disfordavidd

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Link to JIRA task

https://25maikelo.atlassian.net/browse/LABSHARE-10?atlOrigin=eyJpIjoiOTU2MTRiMjBmNWYzNGZkNjk1MmFhMTAxN2NjNWFmZjIiLCJwIjoiaiJ9

## Description (What/Why/How has changed)

-Añadida app David
-Modelo Sillas creado
-Se añadieron los serializadores genéricos CRUD usando Views basados en clases

## Images/Screenshots

## What reviewer should know

## [optional] What gif best describes this PR or how it makes you feel?

![alt_text](gif_link)

2024-05-20 20:28 UTC, 25maikelo requested changes

2024-05-20 20:28 UTC, 25maikelo commented on David/migrations/__init__.py
Este archivo no debería estar en el repo, ni su carpeta

2024-05-20 20:28 UTC, 25maikelo commented on David/admin.py
> +# Register your models here.
Registrar el modelo creado permitira poder gestionarlo desde el administrador si es necesario,

2024-05-24 01:45 UTC, disfordavidd commented on David/migrations/__init__.py
El __init__.py va por defecto al crear la app, se necesita para que funcionen las migraciones, aún así debería retirarse? Al bajar el repo y no tener el __init__.py no permitirá hacer migraciones en la app

2024-05-24 13:27 UTC, 25maikelo approved these changes

2024-05-24 13:27 UTC, 25maikelo commented on David/urls.py
> +]
Deberías poder colocar los 4 métodos del CRUD en una sola línea, solo tienes 1 aqui que es R (read)

2024-05-24 13:27 UTC, 25maikelo commented on David/views.py
> +class silla_list(generics.ListCreateAPIView):
con restframework puedes crear todos los métodos genéricos usando una sola clase y es lo mismo que te permite generar una sola línea de codigo para todas las urls

2024-05-24 13:27 UTC, 25maikelo commented on David/migrations/__init__.py
Idealmente la carpeta *migrations* no se sube al repo. No es eliminarlo es agregar la carpeta al gitignore. La razón de esto es que al no subirse las migraciones estás subiendo una carpeta con un archivo vacío. Si alguien baja el repo y ejecuta makemigrations está carpeta se crea en automático con el init

2024-05-24 19:49 UTC, merged