Práctica 4 Pylint
disfordavidd/rest_test pull request #6
Opened 2024-05-30 03:35 UTC by jmDevstro

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [X ] Documentation Update

## Link to JIRA task
https://25maikelo.atlassian.net/jira/software/projects/LABSHARE/boards/1?selectedIssue=LABSHARE-14

## Description (What/Why/How has changed)
- Actualización de los archivos de código dentro de la app Juan, siguiendo las indicaciones de la herramienta de buenas prácticas pylint

## Images/Screenshots
![Practica 4](https://github.com/disfordavidd/rest_test/assets/166676973/49386cf8-8de1-4c08-8933-d6d7143e3a1a)

## What reviewer should know
- Verificar que se tiene instalado pylint 'pip install pylint', en especial si se utiliza un entorno virtual.

## [optional] What gif best describes this PR or how it makes you feel?

![alt_text](gif_link)

2024-05-30 19:00 UTC, 25maikelo requested changes

2024-05-30 19:00 UTC, 25maikelo commented on Juan/tests.py
> +Test de la app
Para agregar docstrings de modulo tienes que pensar que este archivo puedes aislarlo y aún saber a qué app pertenece, por lo que sugiero que coloques "Tests de app Juan" para que indiques explícitamente a dónde pertenece. De igual manera todos los módulos.

2024-06-06 01:19 UTC, jmDevstro commented on Juan/tests.py
> +Test de la app
Se actualizaron los docstrings de la app Juan para que indiquen que pertenecen a la misma.

2024-06-06 01:47 UTC, 25maikelo approved these changes
Excelente!

2024-06-06 01:47 UTC, merged